project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!prepare/"
    - "!README.md"

resources:
  - img

website:
  title: "JAMES Workshop"
  navbar:
    left:
      - href: program.qmd
        text: Programma
      - text: "Onderwerpen"
        menu:
          - text: "JAMES"
            href: introductie.qmd
          - text: "D-score"
            href: dscore.qmd
          - text: "SDS"
            href: sds.qmd
          - text: "Dynamisch Diagram"
            href: dynamisch-diagram.qmd
          - text: "Tafel van Tien"
            href: tafel-van-tien.qmd
      - text: Practica
        menu:
          - text: "Practicum 1"
            href: practicum_1.qmd
          - text: "Practicum 2"
            href: practicum_2.qmd
          - text: "Practicum 3"
            href: practicum_3.qmd
      - href: API.qmd
        text: API

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

margin-header: |
  <img src="img/tno-logo.svg" alt="TNO logo" style="height: 50px;" />
